<?php
use Singly\Module;
?>

<style>
    ul.api-services li {
        display: inline;
        padding: 3px;
    }

    ul.api-services img {
        border-bottom: solid;
        border-width: 2px;
        padding: 1px;
    }

    ul.api-services img.hover {
        cursor: pointer;
    }

    ul.api-services img.loggedIn {
        border-color: green;
    }

    ul.api-services img.loggedOut {
        border-color: red;
    }
</style>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>

<script>
$(function() {
    // Fade in images so there isn't a color "pop" document load and then on window load

    // clone image
    $('.api-services img').each(function(){
        if ($(this).attr('auth') == 'false') {
            $(this).addClass('loggedOut');
        } else {
            $(this).addClass('loggedIn');
        }
    });

    $('.api-services img').click(function(event) {
        if ($(this).attr('auth') == 'true') return;
        window.location = "https://api.singly.com/oauth/authorize?" +
            "client_id=<?= Module::getOption('client_id'); ?>&" +
            "redirect_uri=<?= Module::getOption('redirect_uri'); ?>&" +
            "service=" + $(this).attr('service');
        return false;
    });

    $('.api-services img').hover(function(event) {
        if ($(this).attr('auth') == 'false') $(this).addClass('hover');
    },
    function(event) {
        $(this).removeClass('hover');
    });
});
</script>

<?php

$profiles = $this->singly()->getProfiles();

?>

<ul class="api-services">
    <li>
        <img title="Tumblr" alt="Tumblr" service="tumblr" auth="<?= (isset($profiles->tumblr)) ? 'true': 'false'; ?>" src="/assets/Singly/images/tumblr.png">
    </li>
    <li>
        <img title="Facebook" alt="Facebook" service="facebook" auth="<?= (isset($profiles->facebook)) ? 'true': 'false'; ?>" src="/assets/Singly/images/facebook.png">
    </li>
    <li>
        <img title="Foursquare" alt="Foursquare" service="foursquare" auth="<?= (isset($profiles->foursquare)) ? 'true': 'false'; ?>" src="/assets/Singly/images/foursquare.png">
    </li>
    <li>
        <img title="Github" alt="Github" service="github" auth="<?= (isset($profiles->github)) ? 'true': 'false'; ?>" src="/assets/Singly/images/github.png">
    </li>
    <li>
        <img title="Instagram" alt="Instagram" service="instagram" auth="<?= (isset($profiles->instagram)) ? 'true': 'false'; ?>" src="/assets/Singly/images/instagram.png">
    </li>
    <li>
        <img title="Twitter" alt="Twitter" service="twitter" auth="<?= (isset($profiles->twitter)) ? 'true': 'false'; ?>" src="/assets/Singly/images/twitter.png">
    </li>
    <li>
        <img title="Google" alt="Google" service="gcontacts" auth="<?= (isset($profiles->gcontacts)) ? 'true': 'false'; ?>" src="/assets/Singly/images/gcontacts.png">
    </li>
    <li>
        <img title="LinkedIN" alt="Linkedin" service="linkedin" auth="<?= (isset($profiles->linkedin)) ? 'true': 'false'; ?>" src="/assets/Singly/images/linkedin.png">
    </li>
    <li>
        <img title="Email" alt="Email" service="email" auth="<?= (isset($profiles->email)) ? 'true': 'false'; ?>" src="/assets/Singly/images/email.png">
    </li>
    <li>
        <img title="Fitbit" alt="Fitbit" service="fitbit" auth="<?= (isset($profiles->fitbit)) ? 'true': 'false'; ?>" src="/assets/Singly/images/fitbit.png">
    </li>
    <li>
        <img title="Wordpress" alt="Wordpress" service="wordpress" auth="<?= (isset($profiles->wordpress)) ? 'true': 'false'; ?>" src="/assets/Singly/images/wordpress.png">
    </li>
</ul>

Your userid is <?= $this->singly()->getIdentity(); ?>
<br>
<br>
<a href="/user/logout">Logout</a>


