<?php
namespace Singly;

use Singly\Module;
?>

<style>
    ul.api-services li {
        display: inline;
        padding: 3px;
    }

    ul.api-services img {
        padding: 1px;
    }

    ul.api-services img.hover {
        cursor: pointer;
    }

    ul.api-services img.loggedIn {
        border-color: green;
    }

    ul.api-services img.loggedOut {
        border-color: red;
    }
</style>

<script>
$(function() {
    $('.api-services img').click(function(event) {
        window.location = "https://api.singly.com/oauth/authorize?" +
            "client_id=<?= $this->singly()->getClientId(); ?>&" +
            "redirect_uri=<?= $this->singly()->getRedirectUri(); ?>&" +
            "service=" + $(this).attr('service');
        return false;
    });

    $('.api-services img').hover(function(event) {
        $(this).addClass('hover');
    },
    function(event) {
        $(this).removeClass('hover');
    });
});
</script>

<?php

?>

<h1>Login</h1>

<ul class="api-services">
<?php
    foreach ($config['singly']['services'] as $name => $service) {
?>
    <li>
        <img title="<?= $this->escapeHtml($service['name']); ?>"
            alt="<?= $this->escapeHtml($service['name']); ?>"
            service="<?= $name; ?>"
            auth="<?= (isset($profiles->$name)) ? 'true': 'false'; ?>"
            src="<?= $service['icon']; ?>"
        >
    </li>
<?php
}
?>
</ul>
